var Lang = {
    en: {
        "Need config": "You must create config.js file",
        "Config file create help": "Open config.sample.js, then fill your dropbox app key and secret. And rename config.sample.js to config.js",

        "Dropbox sign in": "Dropbox sign in",
        "You need to sign in by dropbox account." : "You need to sign in by dropbox account.",
        "Authentication error: ": "Authentication error: ",

        "No network": "No network",
        "You need to connect network.": "You need to connect network.",

        "Sign out": "Sign out",
        "Required field is missed!": "Required field is missed!",

        // Register
        "Register": "Register",
        "Type": "Type",
        "Withdrawal": "Withdrawal",
        "Deposit": "Deposit",
        "deposit": "deposit",
        "Transfer": "Transfer",
        "Memo": "Memo",
        "Amount": "Amount",
        "Date": "Date",
        "Category": "Category",
        "Category helper": "You can use 2 level category, by colon(:).",
        "Food": "Food",
        "Dining": "Dining",
        "Account": "Account",
        "My Wallet": "My Wallet",
        "Account helper": "Enter new account, then that`ll be saved.",
        "To account": "To account",
        "Success": "Success",
        "Complete": "Complete",
        " is added to account list. Go account setting, and set properties.": " is added to account list. Go account setting, and set properties.",
        "Enter category to two level using colon(:).": "Enter category to two level using colon(:).",
        "Category level can be only 2. And you cannot use colon(:) on category name.": "Category level can be only 2. And you cannot use colon(:) on category name.",
        "Category name cannot has colon(:).": "Category name cannot has colon(:).",

        // Setting
        "Setting": "Setting",
        "Language": "Language",
        "Language change info": "Refresh to apply language.",
        "Category depth": "Category depth",
        "1 depth": "1 depth",
        "2 depth": "2 depth",
        "App key": "App key",
        "App secret": "App secret",
        "Delete all data.": "Delete all data.",
        "All data deleted.": "All data deleted.",
        "All data will be deleted and you cannot restore it.": "All data will be deleted and you cannot restore it.",
        "Enter this words to below for delete : ": "Enter this words to below for delete : ",
        "Cancel": "Cancel",
        "Delete": "Delete",
        "Words are wrong.": "Words are wrong.",
        "Close": "Close",

        // Account Setting
        "Add Account": "Add Account",
        "Account Setting": "Account Setting",
        "Owner": "Owner",
        "mine": "mine",
        "others": "others",
        "Is in Balance": "Is in Balance",
        "yes": "yes",
        "no": "no",
        "Whether savings": "Whether savings",
        "Savings": "Savings",
        "Not savings": "Not savings",
        "There is no such account.": "There is no such account.",
        "Account Balance:": "Account Balance:",

        // Category Setting
        "Category Setting": "Category Setting",
        "Update": "Update",
        "Add Category": "Add Category",
        "Name": "Name",
        "Add": "Add",
        "update": "update",
        "Warning": "Warning",
        "Category is already exist.": "Category is already exist.",
        "New Name": "New Name",
        "Save": "Save",
        "This has item. So cannot be deleted.": "This has item. So cannot be deleted.",
        "The category already be deleted.": "The category already be deleted.",
        "Move": "Move",
        "There is no such category.": "There is no such category.",

        // Import
        "Import": "Import",
        "Excel type": "Excel type",
        "Naver Moneybook": "Naver Moneybook",
        "Drop xls file to below.": "Drop xls file to below.",
        "Excel file": "Excel file",

        // Weekly
        "Weekly": "Weekly",
        "No content.": "No content.",
        "withdrawal": "withdrawal",
        "Sum": "Sum",

        // Statistics
        "Statistics": "Statistics",
        "Transfer out": "Transfer out",
        "Transfer in": "Transfer in",
        "Balance": "Balance",
        "Withdrawal-like transfer": "Withdrawal-like transfer",
        "Deposit-like transfer": "Deposit-like transfer",
        "Balance by account": "Balance by account",
        "Yearly": "Yearly",
        "Monthly": "Monthly",
        "Whole": "Whole"
    },
    ko: {
        "Need config": "config.js 파일을 만들어야 합니다",
        "Config file create help": "config.sample.js 파일을 열고 드롭박스 app key와 secret을 입력하세요. 그리고 나서 config.sample.js를 config.js로 바꾸세요.",

        "Dropbox sign in": "드롭박스 로그인",
        "You need to sign in by dropbox account." : "드롭박스로 로그인해야 합니다.",
        "Authentication error: ": "인증 오류: ",

        "No network": "인터넷 연결 안 됨",
        "You need to connect network.": "인터넷에 연결돼 있는지 확인해 주세요.",

        "Sign out": "로그아웃",
        "Required field is missed!": "필수 입력값을 빼먹으셨네요!",

        // Register
        "Register": "등록",
        "Type": "종류",
        "Withdrawal": "지출",
        "Deposit": "수입",
        "deposit": "수입",
        "Transfer": "이체",
        "Memo": "내용",
        "Amount": "금액",
        "Date": "날짜",
        "Category": "카테고리",
        "Category helper": "콜론(:)을 이용해서 두 단계까지 카테고리를 설정할 수 있습니다.",
        "Food": "식비",
        "Dining": "저녁",
        "Account": "계좌",
        "My Wallet": "내 지갑",
        "Account helper": "새 계좌를 입력하면 새로 계좌를 만들고 저장하게 됩니다.",
        "To account": "이체할 계좌",
        "Success": "성공",
        "Complete": "완료",
        " is added to account list. Go account setting, and set properties.": " 계좌를 계좌 목록에 새로 추가했습니다. 계좌 설정에 가서 속성을 설정하세요.",
        "Enter category to two level using colon(:).": "콜론(:)을 이용해 카테고리를 두 단계로 적어 주세요.",
        "Category level can be only 2. And you cannot use colon(:) on category name.": "카테고리는 2단계를 넘어갈 수 없고, 카테고리 이름엔 콜론(:)을 넣을 수 없습니다.",

        // Setting
        "Setting": "설정",
        "Language": "언어",
        "Language change info": "언어 설정을 변경한 뒤에는 새로고침해야 적용됩니다.",
        "Category depth": "카테고리 단계",
        "1 depth": "1단계",
        "2 depth": "2단계",
        "App key": "App key",
        "App secret": "App secret",
        "Delete all data.": "전체 데이터 삭제",
        "Really? You can't restore data.": "정말 모든 데이터를 날리겠습니까? 복구할 수 없습니다.",
        "All data deleted.": "전체 데이터를 삭제했습니다.",
        "All data will be deleted and you cannot restore it.": "모든 데이터를 삭제합니다. 이후 복구할 수 없습니다.",
        "Enter this words to below for delete : " :"삭제하려면 이 단어를 아래에 입력하세요 : ",
        "Cancel": "취소",
        "Delete": "삭제",
        "Words are wrong.": "단어가 틀립니다.",
        "Close": "닫기",

        // Account Setting
        "Add Account": "계좌 추가",
        "Account Setting": "계좌 설정",
        "Owner": "소유자",
        "mine": "내 꺼",
        "others": "다른 사람 거",
        "Is in Balance": "잔액에 포함할지",
        "yes": "포함함",
        "no": "포함 안 함",
        "Whether savings": "저금 여부",
        "Savings": "저금",
        "Not savings": "저금 아님",
        "There is no such account.": "그런 계좌는 없습니다.",
        "Account Balance:": "계좌 잔액:",

        // Category Setting
        "Category Setting": "카테고리 설정",
        "Update": "수정",
        "Add Category": "카테고리 추가",
        "Name": "이름",
        "Add": "추가",
        "update": "수정",
        "Warning": "알림",
        "Category is already exist.": "이미 있는 카테고리입니다.",
        "New Name": "새 이름",
        "Save": "저장",
        "This has item. So cannot be deleted.": "이걸로 등록된 내역이 있기 때문에 삭제할 수 없습니다.",
        "The category already be deleted.": "이 카테고리는 이미 삭제됐습니다.",
        "Category name cannot has colon(:).": "카테고리 이름에 콜론(:)이 들어가면 안 됩니다.",
        "Move": "이동",
        "There is no such category.": "그런 카테고리는 없습니다.",

        // Import
        "Import": "가져오기",
        "Excel type": "엑셀 종류",
        "Naver Moneybook": "네이버 가계부",
        "Drop xls file to below.": "엑셀 파일을 여기다 떨구세요.",
        "Excel file": "엑셀 파일",

        // Weekly
        "Weekly": "주간",
        "No content.": "사용 내역이 없습니다.",
        "withdrawal": "지출",
        "Sum": "합계",

        // Statistics
        "Statistics": "통계",
        "Transfer out": "이체해 보냄",
        "Transfer in": "이체 받음",
        "Balance": "잔액",
        "Withdrawal-like transfer": "지출성 이체",
        "Deposit-like transfer": "수입성 이체",
        "Balance by account": "계좌별 잔액",
        "Yearly": "연도별",
        "Monthly": "월별",
        "Whole": "전체"

    }
};